apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: czjuupx70-nodejs
  janus-idp.io/tekton: czjuupx70-nodejs
  backstage.io/kubernetes-id: czjuupx70-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: czjuupx70-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
