apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: czjuupx70-nodejs-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/czjuupx70-nodejs-gitops